# Generated by Django 5.2.15 on 2026-07-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('iphone', 'iphone'), ('Samsung', 'Samsung'), ('GooglePixel', 'GooglePixel'), ('Apple', 'Apple'), ('Hp', 'Hp'), ('Dell', 'Dell'), ('Lee', 'Lee'), ('Wrangler', 'Wrangler'), ('Spykar', 'Spykar'), ('Raymond', 'Raymond')], max_length=100),
        ),
    ]
